### ISSUE TITLE
2.4.4 本机直接内存溢出例子无法复现

### ISSUE THREAD

**Issue by qbosen** [fenixsoft/jvm_book#16]
《深入理解Java虚拟机 第三版》中2.4.4 本机直接内存溢出例子无法复现。
```
/**
 * VM Args:-Xmx20M -XX:MaxDirectMemorySize=10M
 */
public class DirectMemoryOOM {
    private static final int _1MB = 1024*1024;

    public static void main(String[] args) throws IllegalAccessException {
        Field unsafeField = Unsafe.class.getDeclaredFields()[0];
        unsafeField.setAccessible(true);
        Unsafe unsafe = (Unsafe) unsafeField.get(null);
        while (true){
            unsafe.allocateMemory(_1MB);
        }
    }
}
```
> 系统版本：macOS 10.13.4
JDK:1.8.0_172, 11.0.5, 13.0.1

**Comment by fenixsoft** [comment]
``` bash
java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

java -Xmx20M -XX:MaxDirectMemorySize=10M org.fenixsoft.jvm.chapter2.DirectMemoryOOM
Exception in thread "main" java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at org.fenixsoft.jvm.chapter2.DirectMemoryOOM.main(DirectMemoryOOM.java:21)

java -version
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

java -Xmx20M -XX:MaxDirectMemorySize=10M org.fenixsoft.jvm.chapter2.DirectMemoryOOM
Exception in thread "main" java.lang.OutOfMemoryError
        at java.base/jdk.internal.misc.Unsafe.allocateMemory(Unsafe.java:618)
        at jdk.unsupported/sun.misc.Unsafe.allocateMemory(Unsafe.java:461)
        at org.fenixsoft.jvm.chapter2.DirectMemoryOOM.main(DirectMemoryOOM.java:21)
```

用的是windows 10环境，在家没有macos环境。不同系统、不同发行商、不同虚拟机表现有差异并不奇怪。前面提示过：

> 内存溢出异常与虚拟机本身的实现细节密切相关，并非全是Java语言中约定的公共行为。因此，不同发行商、不同版本的Java虚拟机，其需要的参数和程序运行的结果都很可能会有所差别。

**Comment by qbosen** [comment]
[引用下知乎回答](https://www.zhihu.com/question/385455452/answer/1132014175)
> Unsafe::allocateMemory()要想OOM的话 应该是需要设置一下java进程堆可用的最大空间（注意这里说的不是jvm里面的堆 是linux层级的进程概念中的堆 ）

今天在Ubuntu18.04也进行了尝试。通过`ulimit -u -v`也无法成功抛出OOM。
`ulimit -u50000; java -Xmx20M -XX:MaxDirectMemorySize=10M DirectMemoryOOM`
那在*nix系统中，要如何(能不能)通过`Unsafe`操作产生`OOM`呢？

**Comment by fenixsoft** [comment]
查看代码，Unsafe::allocateMemory()并没有检查MaxDirectMemorySize的行为（这个参数只在Bits等地方通过Java代码生效，以限制堆外内存最大值）。因此是否抛出OOME，取决于os:malloc的执行结果，这个是平台相关的，winnt和*nix可能存在的系统差异。

``` cpp
UNSAFE_ENTRY(jlong, Unsafe_AllocateMemory(JNIEnv *env, jobject unsafe, jlong size))
  UnsafeWrapper("Unsafe_AllocateMemory");
  size_t sz = (size_t)size;
  if (sz != (julong)size || size < 0) {
    THROW_0(vmSymbols::java_lang_IllegalArgumentException());
  }
  if (sz == 0) {
    return 0;
  }
  sz = round_to(sz, HeapWordSize);
  void* x = os::malloc(sz);
  if (x == NULL) {
    THROW_0(vmSymbols::java_lang_OutOfMemoryError());
  }
  //Copy::fill_to_words((HeapWord*)x, sz / HeapWordSize);
  return addr_to_java(x);
UNSAFE_END
```

另，通过ulimit和cgroups都可以限制JVM进程的内存用量：
```bash
# root @ icyfenix.work in ~/develop/jvm_book/src [12:45:53] 
$ ulimit -v 3000000                                                                  

# root @ icyfenix.work in ~/develop/jvm_book/src [12:45:59] 
$ java -Xmx10M -XX:MaxDirectMemorySize=10M org.fenixsoft.jvm.chapter2.DirectMemoryOOM
Exception in thread "main" java.lang.OutOfMemoryError
        at java.base/jdk.internal.misc.Unsafe.allocateMemory(Unsafe.java:616)
        at jdk.unsupported/sun.misc.Unsafe.allocateMemory(Unsafe.java:462)
        at org.fenixsoft.jvm.chapter2.DirectMemoryOOM.main(DirectMemoryOOM.java:21)
```

```bash
# root @ icyfenix.work in ~/develop/jvm_book/src [12:43:23] 
$ systemd-run --scope -p MemoryLimit=30M java -Xmx20M -XX:MaxDirectMemorySize=10M org.fenixsoft.jvm.chapter2.DirectMemoryOOM
Running scope as unit: run-r6c8fe09efc904258ac352f8c7b4e0a0e.scope
[1]    24897 killed     systemd-run --scope -p MemoryLimit=30M java -Xmx20M  
```
