### ISSUE TITLE
Page 64 代码2-9 内存溢出异常的问题/疑惑

### ISSUE THREAD

**Issue by majiaxin110** [fenixsoft/jvm_book#45]
书中写到在JDK 7中的运行结果会有 java.lang.OutOfMemoryError: PermGen space，但我在windows和macOS下的JDK 1.7.0_80 都只能得到简单的"Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"" 这样的提示，如果使用JDK 6的话倒是有PermGen space的错误信息了。想问下JDK 7没有给出错误调用栈和“PermGen space“信息是和JDK7的具体小版本有关系呢，还是我的理解/操作有误？

![JDK6 中可以](https://gitee.com/majiaxin110/my_images/raw/master/小书匠/1595237073655.png)

![JDK7 中不行](https://gitee.com/majiaxin110/my_images/raw/master/小书匠/1595237370102.png)

**Comment by majiaxin110** [comment]
实际上我在stackoverflow上发现似乎[有和我类似情况的问题](https://stackoverflow.com/questions/44948125/exception-java-lang-outofmemoryerror-thrown-from-the-uncaughtexceptionhandler-i#)，可惜没有有效解答

**Comment by fenixsoft** [comment]
如[置顶帖](https://github.com/fenixsoft/jvm_book/issues/17)中提到的，有疑问先在知乎、sf等公众网站提出，但未得到解答的，就很欢迎在这里交流。楼主这个就是标准姿势：）

关于您的问题，我下载了7u80跟踪了一下。结论是异常仍然是PermGen Space OOM，只是CGLib自己捕获了，然后包装成新的异常（net.sf.cglib.core.CodeGenerationException），但是CGLib在处理该异常时，由于永久代已经OOM了，无法再加载其他类，连在控制台打印输出StackTrace的都做不到，所以楼主看不到完整的异常信息。

```log
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main
```

请注意这句打印的其实已经不是Java异常，实际上是HotSpot中的C++代码打印的，只是刻意打印成类似于Java异常堆栈的样子而已。
``` cpp
jio_fprintf(defaultStream::error_stream(),
                "\nException: %s thrown from the UncaughtExceptionHandler"
                " in thread \"%s\"\n",
```

如何证实以上所说的呢？把打印StackTrace所需的类在OOM前先加载好，有了堆栈就好办了。在代码中增加一行：

```java
    public static void main(String[] args) {
        (new Exception()).printStackTrace();     // 增加这一行，把打印堆栈的类先加载好再让PermGen Space OOM

        while (true) {
            Enhancer enhancer = new Enhancer();
            enhancer.setSuperclass(OOMObject.class);
            enhancer.setUseCache(false);
            enhancer.setCallback(new MethodInterceptor() {
                public Object intercept(Object obj, Method method, Object[] args, MethodProxy proxy) throws Throwable {
                    return proxy.invokeSuper(obj, args);
                }
            });
            enhancer.create();
        }
    }
```

输出堆栈如下：

```log
java.lang.Exception
	at org.fenixsoft.jvm.chapter2.JavaMethodAreaOOM.main(JavaMethodAreaOOM.java:17)

Exception in thread "main" net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:237)
	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
	at net.sf.cglib.proxy.Enhancer.create(Enhancer.java:285)
	at org.fenixsoft.jvm.chapter2.JavaMethodAreaOOM.main(JavaMethodAreaOOM.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.sf.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:384)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219)
	... 3 more
Caused by: java.lang.OutOfMemoryError: PermGen space
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	... 8 more
```

**Comment by majiaxin110** [comment]
太感谢了，我没有想到是CGLib的操作
